documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "README.md"
          - "README-*.md"
          - "zensical.toml"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

build:
  - changed-files:
      - any-glob-to-any-file:
          - "pyproject.toml"

chore:
  - changed-files:
      - any-glob-to-any-file:
          - ".pre-commit-config.yaml"
          - ".readthedocs.yaml"
          - "codedev.yml"
          - "bandit.yml"
          - "renovate.json"

correlation.ci:
  - changed-files:
      - any-glob-to-any-file:
          - "src/pystatpower/correlation/ci.py"

correlation.inequality:
  - changed-files:
      - any-glob-to-any-file: "src/pystatpower/correlation/inequality.py"

mean.single.ci:
  - changed-files:
      - any-glob-to-any-file: "src/pystatpower/mean/single/ci.py"

mean.single.inequality:
  - changed-files:
      - any-glob-to-any-file: "src/pystatpower/mean/single/inequality.py"

mean.single.noninferiority:
  - changed-files:
      - any-glob-to-any-file: "src/pystatpower/mean/single/noninferiority.py"

mean.independent.ci:
  - changed-files:
      - any-glob-to-any-file: "src/pystatpower/mean/independent/ci.py"

mean.independent.inequality:
  - changed-files:
      - any-glob-to-any-file: "src/pystatpower/mean/independent/inequality.py"

mean.independent.noninferiority:
  - changed-files:
      - any-glob-to-any-file: "src/pystatpower/mean/independent/noninferiority.py"

mean.independent.superiority:
  - changed-files:
      - any-glob-to-any-file: "src/pystatpower/mean/independent/superiority.py"

proportion.single.ci:
  - changed-files:
      - any-glob-to-any-file: "src/pystatpower/proportion/single/ci.py"
