# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

fail_fast: false
ci:
  autofix_commit_msg: |
    chore: auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-illegal-windows-names
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: name-tests-test
        args: [ --pytest-test-first ]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/opensource-nepal/commitlint
    rev: v1.3.0
    hooks:
      - id: commitlint
