# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

python:
  install:
    - method: uv
      command: sync
      groups:
        - docs

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: latest
  jobs:
    pre_build:
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH
    build:
      html:
        - uv run zensical build
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/
      - cp --recursive site/* $READTHEDOCS_OUTPUT/html/
