site_name: pystatpower
site_url: https://pystatpower.readthedocs.io
repo_url: https://github.com/Snoopy1866/pystatpower
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 - 2026 Snoopy1866

nav:
  - 首页: index.md
  - API:
      - 比例模型:
          - api/models/proportion/index.md
          - api/models/proportion/single.md
          - api/models/proportion/independent.md

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  language: zh
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view

    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top

    - toc.follow
    - toc.integrate

    - search.suggest
    - search.highlight
    - search.share

    - header.autohide

plugins:
  - search:
      lang:
        - zh
        - en
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      enabled: true
      repository: Snoopy1866/pystatpower
      branch: main
  - include-markdown

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
