name: PyTest

on:
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    shell: bash -e {0}

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.filter.outputs.code}}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            code:
              - "src/**"
              - "tests/**"
              - "pyproject.toml"
              - "codecov.yml"
              - ".github/workflows/pytest.yml"

  test-core:
    needs: check-paths
    if: ${{ needs.check-paths.outputs.should_run == 'true' }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    name: test-core (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "0.11.29"
          python-version: ${{ matrix.python-version }}

      - name: Update the environment and test with python ${{ matrix.python-version }}
        run: |
          uv sync --locked --group dev
          uv run --frozen pytest --cov=pystatpower --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: test-core-${{ matrix.os }}-py${{ matrix.python-version }}

  test-minimum-scipy:
    needs: check-paths
    if: ${{ needs.check-paths.outputs.should_run == 'true' }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        deps:
          - python-version: "3.10"
            scipy-version: "1.7.2"
          - python-version: "3.11"
            scipy-version: "1.10.1"
          - python-version: "3.12"
            scipy-version: "1.11.3"
          - python-version: "3.13"
            scipy-version: "1.15.0"
          - python-version: "3.14"
            scipy-version: "1.16.1"

    name: test-minimum-scipy (${{ matrix.os }}, ${{ matrix.deps.python-version }}, scipy == ${{ matrix.deps.scipy-version }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "0.11.29"
          python-version: ${{ matrix.deps.python-version }}

      - name: Update the environment and test with python ${{ matrix.deps.python-version }}
        run: |
          uv sync --locked --group dev
          uv pip install scipy==${{ matrix.deps.scipy-version }} --no-build
          uv run --frozen pytest --cov=pystatpower --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: test-minimum-scipy-${{ matrix.os }}-py${{ matrix.deps.python-version }}-scipy${{ matrix.deps.scipy-version }}

  check-pytest-status:
    needs: [check-paths, test-core, test-minimum-scipy]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check Jobs Status
        run: |
          CHECK_PATH_RESULT="${{ needs.check-paths.result }}"
          PYTEST_CORE_RESULT="${{ needs.test-core.result }}"
          PYTEST_MINIMUM_SCIPY_RESULT="${{ needs.test-minimum-scipy.result }}"

          echo "check-paths status: ${CHECK_PATH_RESULT}"
          echo "test-core status: ${PYTEST_CORE_RESULT}"
          echo "test-minimum-scipy: ${PYTEST_MINIMUM_SCIPY_RESULT}"

          if [ "$CHECK_PATH_RESULT" = "failure" ] || [ "$CHECK_PATH_RESULT" = "cancelled" ]; then
            echo "❌ Path check failed or cancelled."
            exit 1
          fi

          if [ "$PYTEST_CORE_RESULT" = "failure" ] || [ "$PYTEST_CORE_RESULT" = "cancelled" ]; then
            echo "❌ PyTest core test failed or cancelled."
            exit 1
          fi

          if [ "$PYTEST_MINIMUM_SCIPY_RESULT" = "failure" ] || [ "$PYTEST_MINIMUM_SCIPY_RESULT" = "cancelled" ]; then
            echo "❌ PyTest minimum SciPy test failed or cancelled."
            exit 1
          fi

          echo "✅ All tests passed or gracefully skipped!"
