name: PyTest

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

defaults:
  run:
    shell: bash -e {0}

jobs:
  test-core:
    if: ${{ github.event.pull_request.draft == false }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    name: test-core (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "0.11.13"
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --group dev

      - name: Test with python ${{ matrix.python-version }}
        run: |
          uv run --frozen pytest --cov=pystatpower --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: test-core-${{ matrix.os }}-py${{ matrix.python-version }}

  test-minimum-scipy:
    if: ${{ github.event.pull_request.draft == false }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        deps:
          - python-version: "3.10"
            scipy-version: "1.7.2"
          - python-version: "3.11"
            scipy-version: "1.10.1"
          - python-version: "3.12"
            scipy-version: "1.11.3"
          - python-version: "3.13"
            scipy-version: "1.15.0"
          - python-version: "3.14"
            scipy-version: "1.16.1"

    name: test-minimum-scipy (${{ matrix.os }}, ${{ matrix.deps.python-version }}, scipy == ${{ matrix.deps.scipy-version }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "0.11.13"
          python-version: ${{ matrix.deps.python-version }}

      - name: Install the project
        run: uv sync --locked --group dev

      - name: Install SciPy
        run: uv pip install scipy==${{ matrix.deps.scipy-version }} --no-build

      - name: Test with python ${{ matrix.deps.python-version }}
        run: |
          uv run --frozen pytest --cov=pystatpower --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: test-minimum-scipy-${{ matrix.os }}-py${{ matrix.deps.python-version }}-scipy${{ matrix.deps.scipy-version }}
