name: PyTest for all SciPy minor versions

on:
  push:
    branches: ["main"]

defaults:
  run:
    shell: bash -e {0}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        name: Initialize matrix
        run: |
          # 使用 Shell 生成 JSON 对象列表
          JSON_STUFF=$( (
            # Py 3.10: 1.7 ~ 1.15
            for v in $(seq 7 15); do echo "{\"python\":\"3.10\",\"scipy\":\"1.$v\"}"; done
            # Py 3.11: 1.10 ~ 1.17
            for v in $(seq 10 17); do echo "{\"python\":\"3.11\",\"scipy\":\"1.$v\"}"; done
            # Py 3.12: 1.11 ~ 1.17
            for v in $(seq 11 17); do echo "{\"python\":\"3.12\",\"scipy\":\"1.$v\"}"; done
            # Py 3.13: 1.15 ~ 1.17
            for v in $(seq 15 17); do echo "{\"python\":\"3.13\",\"scipy\":\"1.$v\"}"; done
            # Py 3.14: 1.16 ~ 1.17
            for v in $(seq 16 17); do echo "{\"python\":\"3.14\",\"scipy\":\"1.$v\"}"; done
          ) | jq -sc '{"include": .}' )

          echo "matrix=$JSON_STUFF" >> $GITHUB_OUTPUT
  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}

    name: python ${{ matrix.python }}, scipy ${{ matrix.scipy }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: "0.11.21"
          python-version: ${{ matrix.python }}

      - name: Update the environment and test with python ${{ matrix.python }} and SciPy ${{ matrix.scipy }}
        run: |
          uv sync --locked --group dev
          uv pip install scipy~=${{ matrix.scipy }}.0 --no-build
          uv run --frozen pytest --cov=pystatpower --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: test-full-py${{ matrix.python }}-scipy${{ matrix.scipy }}
